### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by kcmojack** [shin10/MMM-FF-Genius-Lyrics#2]
ello dk if this is still active. but i installed this and it says "loading..." forever, it grabs the song but doesnt get lyrics

**Comment by shin10** [comment]
Hi,

haven't had my mirror up for a long time, but just checked and it's still working for me. I don't see updates to the dependencies, so there shouldn't be an issue with that.

Your API key is correct?
Can you see any error in the logs?

**Comment by shin10** [comment]
Were you able to resolve your issue?

**Comment by shin10** [comment]
Possibly the same like #3?
