### ISSUE TITLE
"Spotify Connected"

### ISSUE THREAD

**Issue by buscms123** [shin10/MMM-FF-Genius-Lyrics#3]
I'm only seeing "Spotify Connected" while spotify is playing, no lyrics. Am I missing something? Does this have an issue working with "Pages" ? Thanks!

**Comment by buscms123** [comment]
config for spotify and Genius with api removed 



{
  module: "MMM-Spotify",
  position: "fullscreen_below", // "bottom_bar" or "top_bar" for miniBar
  config: {
    debug: false, // debug mode
    style: "default", // "default" or "mini" available (inactive for miniBar)
    moduleWidth: 1100, // width of the module in px
    control: "default", // "default" or "hidden"
    showAlbumLabel: true, // if you want to show the label for the current song album
    showVolumeLabel: true, // if you want to  show the label for the current volume
    showAccountName: false, // also show the current account name in the device label; usefull for multi account setup
    showAccountButton: true, // if you want to show the "switch account" control button
    showDeviceButton: true, // if you want to show the "switch device" control button
    useExternalModal: false, // if you want to use MMM-Modal for account and device popup selection instead of the build-in one (which is restricted to the album image size)
    updateInterval: 1000, // update interval when playing
    idleInterval: 30000, // update interval on idle
    defaultAccount: 0, // default account number, attention : 0 is the first account
    defaultDevice: null, // optional - if you want the "SPOTIFY_PLAY" notification to also work from "idle" status, you have to define your default device here (by name)
    allowDevices: [], //If you want to limit devices to display info, use this. f.e. allowDevices: ["RASPOTIFY", "My Home speaker"],
    onStart: null, // disable onStart feature with `null`
    // if you want to send custom notifications when suspending the module, f.e. switch MMM-Touch to a different "mode"
    notificationsOnSuspend: [
      {
        notification: "TOUCH_SET_MODE",
        payload: "myNormalMode",
      },
      {
        notification: "WHATEVERYOUWANT",
        payload: "sendMe",
      }
    ],
    // if you want to send custom notifications when resuming the module, f.e. switch MMM-Touch to a different "mode"
    notificationsOnResume: [
      {
        notification: "TOUCH_SET_MODE",
        payload: "mySpotifyControlMode",
      },
    ],
    deviceDisplay: "Listening on", // text to display in the device block (default style only)
    volumeSteps: 5, // in percent, the steps you want to increase or decrese volume when reacting on the "SPOTIFY_VOLUME_{UP,DOWN}" notifications
    // miniBar is no longer supported, use at your own "risk". Will be removed in a future version
    miniBarConfig: {
      album: true, // display Album name in miniBar style
      scroll: true, // scroll title / artist / album in miniBar style
      logo: true, // display Spotify logo in miniBar style
    }
  }
},

{
  module: "MMM-FF-Genius-Lyrics",
  position: "fullscreen_below",
  header: "Genius Lyrics",
  classes: "custom-genius-lyrics",
  config: {
    apiKey: "${APIKEYHERENOQUOTES}", // your CLIENT ACCESS TOKEN from https://genius.com/api-clients
    lyricsClasses: ["medium" , "bold", "italic"]
  }
},

**Comment by shin10** [comment]
Hi @buscms123,

the module is usually working fine with `pages`. I assume you didn't remove the wrapping `${...}` from the API key. Sorry if my notation was misleading.
If this doesn't help, I just committed a change to display error messages returned by the server. 

regards

Michael

**Comment by buscms123** [comment]
Such a simple thing I should have tried. Thanks for the help!
